development:
  adapter: postgresql
  encoding: unicode
  database: zforum_development
  pool: 5
  username: postgres
  password: Kopalnia1

test:
  adapter: postgresql
  encoding: unicode
  database: zforum_test
  pool: 5
  username: postgres
  password: Kopalnia1

production:
  adapter: postgresql
  encoding: unicode
  database: zforum_production
  pool: 5
  username: postgres
  password: Kopalnia1